In [1]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\green\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\green\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
dirtydata = pd.read_excel("C:/Users/Green/Documents/dirtydata.xlsx")
dirtydata

          Duration        Date    Pulse    Maxpulse   Calories
0               60  '2020/12/01'     110        130      409.1
1               60  '2020/12/02'     117        145      479.0
2               60  '2020/12/03'     103        135      340.0
3               45  '2020/12/04'     109        175      282.4
4               45  '2020/12/05'     117        148      406.0
5               60  '2020/12/06'     102        127      300.0
6               60  '2020/12/07'     110        136      374.0
7              450  '2020/12/08'     104        134      253.3
8               30  '2020/12/09'     109        133      195.1
9               60  '2020/12/10'      98        124      269.0
10              60  '2020/12/11'     103        147      329.3
11              60  '2020/12/12'     100        120      250.7
12              60  '2020/12/12'     100        120      250.7
13              60  '2020/12/13'     106        128      345.3
14              60  '2020/12/14'     104        132      379.3
15              60  '2020/12/15'      98        123      275.0
16              60  '2020/12/16'      98        120      215.2
17              60  '2020/12/17'     100        120      300.0
18              45  '2020/12/18'      90        112        NaN
19              60  '2020/12/19'     103        123      323.0
20              45  '2020/12/20'      97        125      243.0
21              60  '2020/12/21'     108        131      364.2
22              45           NaN     100        119      282.0
23              60  '2020/12/23'     130        101      300.0
24              45  '2020/12/24'     105        132      246.0
25              60  '2020/12/25'     102        126      334.5
26              60    2020/12/26     100        120      250.0
27              60  '2020/12/27'      92        118      241.0
28              60  '2020/12/28'     103        132        NaN
29              60  '2020/12/29'     100        132      280.0
30              60  '2020/12/30'     102        129      380.3
31              60  '2020/12/31'      92        115      243.0

# Cleaning Data

Data cleaning means fixing bad data in your data set.

Bad data coould be

In [4]:
# Extra space within the header 
dirtydata.columns

Index(['      Duration', 'Date  ', 'Pulse ', ' Maxpulse', ' Calories'], dtype='object')

In [5]:
# Identifies any empty cell or column in a data set insull(checks missing value),sum(summarises missing value)
dirtydata.isnull().sum()

      Duration    0
Date              1
Pulse             0
 Maxpulse         0
 Calories         2
dtype: int64

#cleandirtydata = dirtydata.copy()  creates a copy to avoid modifying the original Dataframe directly

Help()

In [6]:
thisdirtydata=dirtydata.copy()

In [18]:
thisdirtydata

          Duration        Date    Pulse    Maxpulse   Calories
0               60  '2020/12/01'     110        130      409.1
1               60  '2020/12/02'     117        145      479.0
2               60  '2020/12/03'     103        135      340.0
3               45  '2020/12/04'     109        175      282.4
4               45  '2020/12/05'     117        148      406.0
5               60  '2020/12/06'     102        127      300.0
6               60  '2020/12/07'     110        136      374.0
7              450  '2020/12/08'     104        134      253.3
8               30  '2020/12/09'     109        133      195.1
9               60  '2020/12/10'      98        124      269.0
10              60  '2020/12/11'     103        147      329.3
11              60  '2020/12/12'     100        120      250.7
12              60  '2020/12/12'     100        120      250.7
13              60  '2020/12/13'     106        128      345.3
14              60  '2020/12/14'     104        132      379.3
15              60  '2020/12/15'      98        123      275.0
16              60  '2020/12/16'      98        120      215.2
17              60  '2020/12/17'     100        120      300.0
18              45  '2020/12/18'      90        112        NaN
19              60  '2020/12/19'     103        123      323.0
20              45  '2020/12/20'      97        125      243.0
21              60  '2020/12/21'     108        131      364.2
22              45           NaN     100        119      282.0
23              60  '2020/12/23'     130        101      300.0
24              45  '2020/12/24'     105        132      246.0
25              60  '2020/12/25'     102        126      334.5
26              60    2020/12/26     100        120      250.0
27              60  '2020/12/27'      92        118      241.0
28              60  '2020/12/28'     103        132        NaN
29              60  '2020/12/29'     100        132      280.0
30              60  '2020/12/30'     102        129      380.3
31              60  '2020/12/31'      92        115      243.0

In [7]:
dirtydata.columns = dirtydata.columns.str.strip()

In [8]:
#Removes empty rows
dirtydata.dropna()

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [9]:
#noemptyrow=dirtydata.dropna()

In [10]:
#noemptyrow.isnull().sum()

In [11]:
dirtydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [12]:
# dropna(inplace = True)
# dirtydata.fillna( ) replaces NaN with 0
# fillna({"calories": 130}, inplace=True) replaces null values in the 'calories' columns with number 130
# duplicate

In [13]:
dirtydata.dropna(inplace = True)
dirtydata

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [15]:
dirtydata.fillna(130)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
dirtydata.fillna({"calories": 130}, inplace=True)

In [17]:
dirtydata.duplicated

<bound method DataFrame.duplicated of     Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0>